ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Service> favServices { get; set; }
    }
}

ViewModels/ServicesListViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ServicesListViewModel
    {
         public IEnumerable<Service> allServices { get; set; }
         public string currCategory { get; set; }

    }
}

ViewModels/ShopServiceViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShopServiceViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private IAllServices _serviceRep;
        

        public HomeController(IAllServices serviceRep)
        {
            _serviceRep = serviceRep;
        }
        public ViewResult Index()
        {
            var homeServices = new HomeViewModel
            {
            favServices = _serviceRep.getFavServices
            };
            return View(homeServices);
        }

    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;
        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItems = shopCart.getShopItems();
            if (shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("", "Товари відсутні!");
            }
            if (ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }


            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Дякуємо за Ваше замовлення!";
            return View();
        }
    }
}

Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ServicesController : Controller
    {
        private readonly IAllServices _allServices;
        private readonly IServicesCategory _allCategories;

        public ServicesController (IAllServices iAllServices, IServicesCategory iServicesCat)
        {
            _allServices = iAllServices;
            _allCategories = iServicesCat;
        }
        [Route("Service/List")]
        [Route("Service/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Service> services = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                services = _allServices.Services.OrderBy(i => i.id);
            }
            else
            {
                if(string.Equals("FullService", category, StringComparison.OrdinalIgnoreCase))
                {
                    services = _allServices.Services.Where(i => i.Category.categoryName.Equals("Повне обслуговування")).OrderBy(i => i.id);
                    currCategory = "Повне обслуговування";
                }
                else if (string.Equals("SelectiveService", category, StringComparison.OrdinalIgnoreCase))
                {
                    services = _allServices.Services.Where(i => i.Category.categoryName.Equals("Вибіркове обслуговування")).OrderBy(i => i.id);
                    currCategory = "Вибіркове обслуговування";
                }
                

               
            }

            var serviceObj = new ServicesListViewModel
            {
                allServices = services,
                currCategory = currCategory
            };
            ViewBag.Title = "Сторінка з послугами";
           
            
            return View(serviceObj);
        }

    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShopCartController : Controller 
    {
        private  IAllServices _serviceRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllServices serviceRep, ShopCart shopCart)
        {
            _serviceRep = serviceRep;
            _shopCart = shopCart;

        }
         
        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopServiceViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);

            
        }
        public RedirectToActionResult addToCart(int id)
        {
            var item = _serviceRep.Services.FirstOrDefault(i => i.id == id);
            if(item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@model HomeViewModel

<h1>Топ послуги</h1>
<div class="row mt-5 md-2">
    @{
        foreach (Service service in Model.favServices)
        {
            @Html.Partial("AllServices", service)
        }

    }
</div>

Views/Order/Checkout.cshtml
@model Order

<div class="row">
    <h3>Оформлення замовлення</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-6">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="surname"></label>
            <div class="col-md-6">
                <input asp-for="surname" class="form-control" />
                <span asp-validation-for="surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="adress"></label>
            <div class="col-md-6">
                <input asp-for="adress" class="form-control" />
                <span asp-validation-for="adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-6">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-6">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Завершити замовлення" />
    </form>
</div>

Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Views/Services/List.cshtml
    <h1>Всi послуги</h1>
    <h3>@Model.currCategory</h3>
    <div class="row mt-5 md-2">
        @{
            foreach (Service service in Model.allServices)
            {
            @Html.Partial("AllServices", service)
            }

         }
    </div>
  

Views/Shared/AllServices.cshtml
@model Shop.Data.Models.Service

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2>@Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Ціна: @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Додати в кошик </a></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark  bg-dark">
            <a class="navbar-brand" href="#">SavePC</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Головна</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Service/List">Послуги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Service/List/SelectiveService">Окремі послуги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Service/List/FullService">Пакети послуг</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ShopCart/">Кошик</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Пошук" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Пошук</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <foother class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>2019 Всі права захищені  <a href="#">Privacy</a>/</p>
    </foother>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Views/ShopCart/Index.cshtml
 @model ShopServiceViewModel
<div class = "container">
@foreach (var el in Model.shopCart.listShopItems)
{
    <div class="alert alert-warning mt-3">
        <b>Сервіс:</b> @el.service.name<br/>
        <b>Ціна:</b>@el.service.price.ToString("c")
    </div>
    }
<hr/>
<a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Сплатити</a>
</div>